language: android
os: linux
dist: xenial
git:
  depth: 1
env:
  global:
  - MINIO_UPLOAD=release
  - DEPLOY_DIR=release
  - DEPLOY_BRANCH=android
  - LIBWINDBOT_URL=https://github.com/edo9300/libWindbot/releases/download/v2/libWindbot.aar
android:
  components:
  - platform-tools
  - tools
  - build-tools-29.0.3
  - android-28
install: yes | sdkmanager ndk-bundle
before_script:
- mkdir -p libs
- curl --retry 5 --connect-timeout 30 --location --remote-header-name -o libs/libWindbot.aar $LIBWINDBOT_URL
script:
- echo "sdk.dir=$ANDROID_HOME" > local.properties
- $ANDROID_HOME/ndk-bundle/ndk-build -j2
- $ANDROID_HOME/ndk-bundle/ndk-build -C deps/ocgcore -j2
- ./download-assets.sh
- ./finalize-assets.sh
- ./gradlew assemble
before_deploy:
- ./sign-release.sh
- cp build/outputs/apk/debug/*.apk build/outputs/apk/release/*.apk release
- rm -f release/*.json
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./travis-minio.sh
